---
title: "2_spp_tax_lookup"
output: html_document
---

## Summary

Here I make a lookup table for the SAU catch commodities, the trade commodities, and redlist info.

While the catch and trade data don't need to be linekd, the prices data is attached to the SAU commodities but to get trade value, need the prices for the trade commodity list

Here the "usd_per_mt" is an average of the 2006 - 2014 records. 
The price database ends in 2010, so 2011-2014 value estimates use the 2010 prices - so using mean compared to 2010 will be similar, but avoids any gap filling

```{r setup, include=FALSE}

library(tidyverse)

```

## match catch databases

full commodity list (not all appear in the trade data)

```{catch dbs}

sau_species <- read_csv("_data/sau_catch/sau_commodities_rl_globalonly.csv")
names(sau_species)

reg_catch_spp <- read_csv("_data/dont_post/reg_catch/catch_commodities_list_decade.csv")

sau_species <- sau_species %>% select(-c(assessment_id:systems))
reg_catch_spp <- reg_catch_spp %>% select(c(species_or_taxon:taxa_group,redlist_category))

## some checks

n_distinct(sau_species$taxon_sciname) # n = 1456
n_distinct(reg_catch_spp$species_or_taxon) # n = 1007

##<><>< match

## full name

reg_only <- anti_join(reg_catch_spp, sau_species, by = c("species_or_taxon" = "taxon_sciname"))
n_distinct(reg_only$species_or_taxon) # n = 131

## genus

reg_only <- reg_only %>%
  mutate(first_word = stringr::word(species_or_taxon, 1)) # extract first word in name

# make intermediary file for first round manual substitution for trade commodities:
write_csv(reg_only, "_data/spp_list_manual_matching.csv")
# Manual matching/substituion steps:
  # 1. Match by name variation (e.g. double species name)
  # 2. Substitute wtih genus or family grouping
  # 3. Substitute with another spp in same genus, where there is only one species in SAU data

## Load data with substitution steps 1,2,3 done manually: 
manual_matching <- read_csv("_data/spp_list_manual_matching.csv")
names(manual_matching)
manual_matching %>% filter(is.na(usd_per_mt)) # n = 109 still need to be filled

manual_matching %>% filter(sau_match == "multiple") %>% summarise(n = n_distinct(species_or_taxon)) # n = 29 spp

## get mean price for each genus (or first word group) in SAU db
sau_spp_short <- sau_species %>% select(c(taxon_sciname, usd_mt_avg))
sau_spp_short <- sau_spp_short %>%
  mutate(first_word_sau = stringr::word(taxon_sciname, 1))
sau_spp_short <- sau_spp_short %>%
  group_by(first_word_sau) %>%
  mutate(price_grp_avg = mean(usd_mt_avg)) %>%
  ungroup()
sau_spp_short <- sau_spp_short %>% distinct(first_word_sau, price_grp_avg)

## 4. replace missing prices with genus/group means
manual_matching_2 <- left_join(manual_matching, sau_spp_short, by = c("first_word" = "first_word_sau")) %>%
  filter(is.na(usd_per_mt)) %>%
  mutate(usd_per_mt = case_when(
    sau_match == "multiple" ~ price_grp_avg
  ))
manual_matching_2 %>% filter(is.na(sau_match)) 
  # 5. n = 80 species need to be manually substituted with a larger group (worst case == "marine fish nei")
write_csv(manual_matching_2, "_data/spp_list_manual_matching_rnd2.csv")

## load matching round 2
manual_matching_2 <- read_csv("_data/spp_list_manual_matching_rnd2.csv")
names(manual_matching_2)

## remove rnd 2 matches from round 1 
names(manual_matching)
nrow(manual_matching) # n = 222
manual_matching <- manual_matching %>% filter(!is.na(usd_per_mt))
nrow(manual_matching) # n = 113
manual_matching <- manual_matching %>% 
  select(c("species_or_taxon","taxonkey","common_name_reg","sau_match","usd_per_mt"))

names(manual_matching_2)
nrow(manual_matching_2) # n = 109
manual_matching_2 <- manual_matching_2 %>% 
  select(c("species_or_taxon","taxonkey","common_name_reg","sau_match","usd_per_mt"))

## bind
manual_matched_final <- bind_rows(manual_matching, manual_matching_2)

## check
nrow(manual_matched_final) # n = 222
n_distinct(manual_matched_final) # n = 220
manual_matched_final %>% filter(is.na(usd_per_mt)) # none


## Make lookup table

reg_matches <- inner_join(reg_catch_spp, sau_species, by = c("species_or_taxon" = "taxon_sciname"))
n_distinct(reg_matches$species_or_taxon) # n = 876 

## remove extra cols
names(reg_matches)
reg_matches <- reg_matches %>% select(-c("taxa_group.y", "redlist_category.y", "tot_catch_mt",
                                       "tot_value_usd", "iucn_taxonid","record_cat"))
reg_matches <- reg_matches %>% 
  rename(taxa_group = "taxa_group.x", redlist_category = "redlist_category.x")

reg_matches$sau_substitute <- NA

## checks
n_distinct(reg_matches$species_or_taxon) # n = 876
reg_matches %>% filter(is.na(usd_mt_2014)) # none

names(manual_matched_final)
n_distinct(manual_matched_final$species_or_taxon) # n = 218
manual_matched_final <- manual_matched_final %>% 
  rename(sau_substitute = sau_match, usd_mt_avg = usd_per_mt)

## add 2014 prices to the manually matched species

names(sau_species)
names(manual_matched_final)

## species matched by a (single) substitute SAU species 
prices_to_add_subst <- left_join(manual_matched_final, sau_species, by = c("sau_substitute" = "taxon_sciname"))
names(prices_to_add_subst)
prices_to_add_subst <- prices_to_add_subst %>% select(-usd_mt_avg.y) %>% rename(usd_mt_avg = usd_mt_avg.x)
prices_to_add_subst <- prices_to_add_subst %>% 
  select(c("species_or_taxon","common_name_reg","taxonkey", "redlist_category", "taxa_group", "usd_mt_avg", "usd_mt_2014", "spp_yn", "sau_substitute"))

n_distinct(prices_to_add_subst$species_or_taxon) # n = 218
prices_to_add_subst %>% filter(!is.na(usd_mt_2014)) # n = 193
prices_to_add_subst <- prices_to_add_subst %>% filter(!is.na(usd_mt_2014))

## replace missing 2014 prices with genus/group means for the 29 spp matching multiple sau species
## get mean price for each genus (or first word group) in SAU db
sau_spp_avgs <- sau_species %>% 
  select(c(taxon_sciname, usd_mt_2014)) %>%
  mutate(first_word_sau = stringr::word(taxon_sciname, 1)) %>%
  group_by(first_word_sau) %>%
  mutate(price_grp_avg_2014 = mean(usd_mt_2014)) %>%
  distinct(first_word_sau, price_grp_avg_2014) %>%
  ungroup()

prices_to_add_avgs <- manual_matched_final %>%
  filter(sau_substitute == "multiple") %>%
  mutate(first_word = stringr::word(species_or_taxon, 1)) %>%
  left_join(sau_spp_avgs, by = c("first_word" = "first_word_sau")) %>%
  mutate(usd_mt_2014 = price_grp_avg_2014)

names(prices_to_add_avgs)
names(prices_to_add_subst)

prices_to_add_avgs <- prices_to_add_avgs %>%
  select(c("species_or_taxon", "taxonkey", "common_name_reg", "sau_substitute", "usd_mt_avg", "usd_mt_2014"))
prices_to_add_subst <- prices_to_add_subst %>%
  select(c("species_or_taxon", "taxonkey", "common_name_reg", "sau_substitute", "usd_mt_avg", "usd_mt_2014"))


## bind
prices_to_add <- bind_rows(prices_to_add_subst, prices_to_add_avgs)
n_distinct(prices_to_add$species_or_taxon) # n = 218
names(prices_to_add)
prices_to_add %>% filter(is.na(usd_mt_2014)) # none

## bind to reg matches

reg_matches %>% filter(is.na(usd_mt_2014))
names(reg_matches)
names(prices_to_add)
reg_matches <- reg_matches %>% select(-c("redlist_category", "spp_yn", "taxa_group"))

spp_lookup <- bind_rows(reg_matches, prices_to_add)

## checks
n_distinct(spp_lookup$species_or_taxon) # n = 1094
library(hablar)
spp_lookup %>% find_duplicates() # 116 dups across all cols
spp_lookup <- spp_lookup %>% distinct()
names(spp_lookup)
spp_lookup %>% filter(is.na(usd_mt_avg)) # none

## save lookup

write_csv(spp_lookup, "_data/reg_catch_spp_prices.csv")

```


## Match catch and trade commodities

First match by species/taxon name,
Then do a series of matching/substituting steps in R and manually 
could replace some of this with fuzzy joins, but many species have a family name completely different from the genus

```{match trade commodities}

## Load data

spp_lookup <- read_csv("_data/reg_catch_spp_prices.csv")

trade <- fread("C://Users//uqlrob10//OneDrive - The University of Queensland//_data//_data_mod//fishing_thspp//reg_trade//trade_decade_w_rl.csv")
names(trade)

trade_species <- trade %>% distinct(species_or_taxon, taxonkey, common_name)
n_distinct(trade_species$species_or_taxon) # n = 466 trade commodities
nrow(trade_species) # n = 485
names(trade_species)
trade_species <- trade_species %>% rename(common_name_reg = common_name)

names(spp_lookup)
spp_lookup %>% filter(is.na(usd_mt_2014)) # none
nrow(spp_lookup) # n = 1099

## test join

temp <- anti_join(trade_species, spp_lookup, by = "taxonkey") # n = 29 species missing
nrow(temp)

## test with full SAU list
sau_species <- read_csv("_data/sau_catch/sau_commodities_rl.csv")
names(sau_species)

temp_2 <- anti_join(trade_species, sau_species, by = c("species_or_taxon" = "taxon_sciname")) # even more nonmatches

## check manually

write_csv(temp, "_data/trade_spp_manual_match.csv")
# they're all in the SAU list, unclear why the name-based join didn't work

## make trade spp price list

trade_spp_prices <- left_join(trade_species, spp_lookup, by = c("taxonkey", "species_or_taxon", "common_name_reg"))

## check

n_distinct(trade_spp_prices$species_or_taxon) # n = 466
trade_spp_prices %>% filter(is.na(usd_mt_2014)) # n = 29 missing
trade_spp_prices <- trade_spp_prices %>% filter(!is.na(usd_mt_2014))

trade_to_add <- read_csv("_data/trade_spp_manual_match.csv")

names(trade_to_add)
names(trade_spp_prices)

## bind

trade_spp_prices <- bind_rows(trade_spp_prices, trade_to_add)

## check
trade_spp_prices %>% find_duplicates() # none
n_distinct(trade_spp_prices$species_or_taxon) # n = 466
trade_spp_prices %>% filter(is.na(usd_mt_2014)) # none


write_csv(trade_spp_prices, "_data/trade_spp_prices.csv")

```

